/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Com.Gridly.Client;
using Com.Gridly.Api;
// uncomment below to import models
//using Com.Gridly.Model;

namespace Com.Gridly.Test.Api
{
    /// <summary>
    ///  Class for testing CdnApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CdnApiTests : IDisposable
    {
        private CdnApi instance;

        public CdnApiTests()
        {
            instance = new CdnApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CdnApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CdnApi
            //Assert.IsType<CdnApi>(instance);
        }

        /// <summary>
        /// Test List
        /// </summary>
        [Fact]
        public void ListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string gridId = null;
            //int? offset = null;
            //int? limit = null;
            //List<string> ids = null;
            //bool? published = null;
            //var response = instance.List(gridId, offset, limit, ids, published);
            //Assert.IsType<List<CDN>>(response);
        }

        /// <summary>
        /// Test Publish
        /// </summary>
        [Fact]
        public void PublishTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cdnId = null;
            //var response = instance.Publish(cdnId);
            //Assert.IsType<CDN>(response);
        }

        /// <summary>
        /// Test UnPublish
        /// </summary>
        [Fact]
        public void UnPublishTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cdnId = null;
            //var response = instance.UnPublish(cdnId);
            //Assert.IsType<CDN>(response);
        }
    }
}
