/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// AutomationTrigger
    /// </summary>
    [DataContract(Name = "AutomationTrigger")]
    public partial class AutomationTrigger : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutomationTrigger" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="type">type.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="triggerType">triggerType.</param>
        /// <param name="watchingColumns">watchingColumns.</param>
        /// <param name="watchingAll">watchingAll.</param>
        /// <param name="enabled">enabled.</param>
        public AutomationTrigger(string id = default, string type = default, string name = default, string description = default, string triggerType = default, List<string> watchingColumns = default, bool watchingAll = default, bool enabled = default)
        {
            this.Id = id;
            this.Type = type;
            this.Name = name;
            this.Description = description;
            this.TriggerType = triggerType;
            this.WatchingColumns = watchingColumns;
            this.WatchingAll = watchingAll;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets TriggerType
        /// </summary>
        [DataMember(Name = "triggerType", EmitDefaultValue = true)]
        public string TriggerType { get; set; }

        /// <summary>
        /// Gets or Sets WatchingColumns
        /// </summary>
        [DataMember(Name = "watchingColumns", EmitDefaultValue = true)]
        public List<string> WatchingColumns { get; set; }

        /// <summary>
        /// Gets or Sets WatchingAll
        /// </summary>
        [DataMember(Name = "watchingAll", EmitDefaultValue = true)]
        public bool WatchingAll { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutomationTrigger {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  TriggerType: ").Append(TriggerType).Append("\n");
            sb.Append("  WatchingColumns: ").Append(WatchingColumns).Append("\n");
            sb.Append("  WatchingAll: ").Append(WatchingAll).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
