/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// BulkExecutionTriggerRequest
    /// </summary>
    [DataContract(Name = "BulkExecutionTriggerRequest")]
    public partial class BulkExecutionTriggerRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkExecutionTriggerRequest" /> class.
        /// </summary>
        /// <param name="automationIds">automationIds.</param>
        /// <param name="await">await.</param>
        public BulkExecutionTriggerRequest(List<string> automationIds = default, bool await = default)
        {
            this.AutomationIds = automationIds;
            this.Await = await;
        }

        /// <summary>
        /// Gets or Sets AutomationIds
        /// </summary>
        [DataMember(Name = "automationIds", EmitDefaultValue = true)]
        public List<string> AutomationIds { get; set; }

        /// <summary>
        /// Gets or Sets Await
        /// </summary>
        [DataMember(Name = "await", EmitDefaultValue = true)]
        public bool Await { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkExecutionTriggerRequest {\n");
            sb.Append("  AutomationIds: ").Append(AutomationIds).Append("\n");
            sb.Append("  Await: ").Append(Await).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
