/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// ColumnReference
    /// </summary>
    [DataContract(Name = "ColumnReference")]
    public partial class ColumnReference : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Row for value: row
            /// </summary>
            [EnumMember(Value = "row")]
            Row = 1,

            /// <summary>
            /// Enum Cell for value: cell
            /// </summary>
            [EnumMember(Value = "cell")]
            Cell = 2
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Defines SelectionType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SelectionTypeEnum
        {
            /// <summary>
            /// Enum Single for value: single
            /// </summary>
            [EnumMember(Value = "single")]
            Single = 1,

            /// <summary>
            /// Enum Multiple for value: multiple
            /// </summary>
            [EnumMember(Value = "multiple")]
            Multiple = 2
        }


        /// <summary>
        /// Gets or Sets SelectionType
        /// </summary>
        [DataMember(Name = "selectionType", EmitDefaultValue = true)]
        public SelectionTypeEnum? SelectionType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ColumnReference" /> class.
        /// </summary>
        /// <param name="grid">grid.</param>
        /// <param name="column">column.</param>
        /// <param name="branch">branch.</param>
        /// <param name="type">type.</param>
        /// <param name="selectionType">selectionType.</param>
        public ColumnReference(ReferencedGrid grid = default, ReferencedColumn column = default, ReferencedGrid branch = default, TypeEnum? type = default, SelectionTypeEnum? selectionType = default)
        {
            this.Grid = grid;
            this.Column = column;
            this.Branch = branch;
            this.Type = type;
            this.SelectionType = selectionType;
        }

        /// <summary>
        /// Gets or Sets Grid
        /// </summary>
        [DataMember(Name = "grid", EmitDefaultValue = true)]
        public ReferencedGrid Grid { get; set; }

        /// <summary>
        /// Gets or Sets Column
        /// </summary>
        [DataMember(Name = "column", EmitDefaultValue = true)]
        public ReferencedColumn Column { get; set; }

        /// <summary>
        /// Gets or Sets Branch
        /// </summary>
        [DataMember(Name = "branch", EmitDefaultValue = true)]
        public ReferencedGrid Branch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ColumnReference {\n");
            sb.Append("  Grid: ").Append(Grid).Append("\n");
            sb.Append("  Column: ").Append(Column).Append("\n");
            sb.Append("  Branch: ").Append(Branch).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  SelectionType: ").Append(SelectionType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
