/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// Defines ExportGlossaryFormat
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ExportGlossaryFormat
    {
        /// <summary>
        /// Enum Csv for value: csv
        /// </summary>
        [EnumMember(Value = "csv")]
        Csv = 1,

        /// <summary>
        /// Enum Xls for value: xls
        /// </summary>
        [EnumMember(Value = "xls")]
        Xls = 2,

        /// <summary>
        /// Enum Xlsx for value: xlsx
        /// </summary>
        [EnumMember(Value = "xlsx")]
        Xlsx = 3,

        /// <summary>
        /// Enum Tbx for value: tbx
        /// </summary>
        [EnumMember(Value = "tbx")]
        Tbx = 4

    }

}
