/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// Grid
    /// </summary>
    [DataContract(Name = "Grid")]
    public partial class Grid : IValidatableObject
    {
        /// <summary>
        /// Defines RecordIdentifierType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RecordIdentifierTypeEnum
        {
            /// <summary>
            /// Enum RecordId for value: recordId
            /// </summary>
            [EnumMember(Value = "recordId")]
            RecordId = 1,

            /// <summary>
            /// Enum PathTagRecordId for value: pathTagRecordId
            /// </summary>
            [EnumMember(Value = "pathTagRecordId")]
            PathTagRecordId = 2
        }


        /// <summary>
        /// Gets or Sets RecordIdentifierType
        /// </summary>
        [DataMember(Name = "recordIdentifierType", EmitDefaultValue = true)]
        public RecordIdentifierTypeEnum? RecordIdentifierType { get; set; }
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Deleted for value: deleted
            /// </summary>
            [EnumMember(Value = "deleted")]
            Deleted = 1,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 2,

            /// <summary>
            /// Enum Inactive for value: inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            Inactive = 3,

            /// <summary>
            /// Enum Restoring for value: restoring
            /// </summary>
            [EnumMember(Value = "restoring")]
            Restoring = 4,

            /// <summary>
            /// Enum BackingUp for value: backingUp
            /// </summary>
            [EnumMember(Value = "backingUp")]
            BackingUp = 5,

            /// <summary>
            /// Enum Uploading for value: uploading
            /// </summary>
            [EnumMember(Value = "uploading")]
            Uploading = 6,

            /// <summary>
            /// Enum Importing for value: importing
            /// </summary>
            [EnumMember(Value = "importing")]
            Importing = 7,

            /// <summary>
            /// Enum Branching for value: branching
            /// </summary>
            [EnumMember(Value = "branching")]
            Branching = 8,

            /// <summary>
            /// Enum Merging for value: merging
            /// </summary>
            [EnumMember(Value = "merging")]
            Merging = 9,

            /// <summary>
            /// Enum Duplicating for value: duplicating
            /// </summary>
            [EnumMember(Value = "duplicating")]
            Duplicating = 10,

            /// <summary>
            /// Enum ClearingRecords for value: clearingRecords
            /// </summary>
            [EnumMember(Value = "clearingRecords")]
            ClearingRecords = 11,

            /// <summary>
            /// Enum Copying for value: copying
            /// </summary>
            [EnumMember(Value = "copying")]
            Copying = 12,

            /// <summary>
            /// Enum UpdatingWorkflow for value: updatingWorkflow
            /// </summary>
            [EnumMember(Value = "updatingWorkflow")]
            UpdatingWorkflow = 13,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            [EnumMember(Value = "archived")]
            Archived = 14
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Grid" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="columns">columns.</param>
        /// <param name="defaultAccessViewId">defaultAccessViewId.</param>
        /// <param name="description">description.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="name">name.</param>
        /// <param name="recordIdentifierType">recordIdentifierType.</param>
        /// <param name="status">status.</param>
        public Grid(string id = default, List<ViewColumn> columns = default, string defaultAccessViewId = default, string description = default, Dictionary<string, string> metadata = default, string name = default, RecordIdentifierTypeEnum? recordIdentifierType = default, StatusEnum? status = default)
        {
            this.Id = id;
            this.Columns = columns;
            this.DefaultAccessViewId = defaultAccessViewId;
            this.Description = description;
            this.Metadata = metadata;
            this.Name = name;
            this.RecordIdentifierType = recordIdentifierType;
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [DataMember(Name = "columns", EmitDefaultValue = true)]
        public List<ViewColumn> Columns { get; set; }

        /// <summary>
        /// Gets or Sets DefaultAccessViewId
        /// </summary>
        [DataMember(Name = "defaultAccessViewId", EmitDefaultValue = true)]
        public string DefaultAccessViewId { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Grid {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  DefaultAccessViewId: ").Append(DefaultAccessViewId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RecordIdentifierType: ").Append(RecordIdentifierType).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
