/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// TranslationCount
    /// </summary>
    [DataContract(Name = "TranslationCount")]
    public partial class TranslationCount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationCount" /> class.
        /// </summary>
        /// <param name="all">all.</param>
        /// <param name="outOfDate">outOfDate.</param>
        /// <param name="unset">unset.</param>
        /// <param name="upToDate">upToDate.</param>
        public TranslationCount(long all = default, long outOfDate = default, long unset = default, long upToDate = default)
        {
            this.All = all;
            this.OutOfDate = outOfDate;
            this.Unset = unset;
            this.UpToDate = upToDate;
        }

        /// <summary>
        /// Gets or Sets All
        /// </summary>
        [DataMember(Name = "all", EmitDefaultValue = true)]
        public long All { get; set; }

        /// <summary>
        /// Gets or Sets OutOfDate
        /// </summary>
        [DataMember(Name = "outOfDate", EmitDefaultValue = true)]
        public long OutOfDate { get; set; }

        /// <summary>
        /// Gets or Sets Unset
        /// </summary>
        [DataMember(Name = "unset", EmitDefaultValue = true)]
        public long Unset { get; set; }

        /// <summary>
        /// Gets or Sets UpToDate
        /// </summary>
        [DataMember(Name = "upToDate", EmitDefaultValue = true)]
        public long UpToDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TranslationCount {\n");
            sb.Append("  All: ").Append(All).Append("\n");
            sb.Append("  OutOfDate: ").Append(OutOfDate).Append("\n");
            sb.Append("  Unset: ").Append(Unset).Append("\n");
            sb.Append("  UpToDate: ").Append(UpToDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
