/*
 * Gridly API
 *
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 6.13.0
 * Contact: support@gridly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Gridly.Client.OpenAPIDateConverter;

namespace Com.Gridly.Model
{
    /// <summary>
    /// View
    /// </summary>
    [DataContract(Name = "View")]
    public partial class View : IValidatableObject
    {
        /// <summary>
        /// Defines GridStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GridStatusEnum
        {
            /// <summary>
            /// Enum Deleted for value: deleted
            /// </summary>
            [EnumMember(Value = "deleted")]
            Deleted = 1,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 2,

            /// <summary>
            /// Enum Inactive for value: inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            Inactive = 3,

            /// <summary>
            /// Enum Restoring for value: restoring
            /// </summary>
            [EnumMember(Value = "restoring")]
            Restoring = 4,

            /// <summary>
            /// Enum BackingUp for value: backingUp
            /// </summary>
            [EnumMember(Value = "backingUp")]
            BackingUp = 5,

            /// <summary>
            /// Enum Uploading for value: uploading
            /// </summary>
            [EnumMember(Value = "uploading")]
            Uploading = 6,

            /// <summary>
            /// Enum Importing for value: importing
            /// </summary>
            [EnumMember(Value = "importing")]
            Importing = 7,

            /// <summary>
            /// Enum Branching for value: branching
            /// </summary>
            [EnumMember(Value = "branching")]
            Branching = 8,

            /// <summary>
            /// Enum Merging for value: merging
            /// </summary>
            [EnumMember(Value = "merging")]
            Merging = 9,

            /// <summary>
            /// Enum Duplicating for value: duplicating
            /// </summary>
            [EnumMember(Value = "duplicating")]
            Duplicating = 10,

            /// <summary>
            /// Enum ClearingRecords for value: clearingRecords
            /// </summary>
            [EnumMember(Value = "clearingRecords")]
            ClearingRecords = 11,

            /// <summary>
            /// Enum Copying for value: copying
            /// </summary>
            [EnumMember(Value = "copying")]
            Copying = 12,

            /// <summary>
            /// Enum UpdatingWorkflow for value: updatingWorkflow
            /// </summary>
            [EnumMember(Value = "updatingWorkflow")]
            UpdatingWorkflow = 13,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            [EnumMember(Value = "archived")]
            Archived = 14
        }


        /// <summary>
        /// Gets or Sets GridStatus
        /// </summary>
        [DataMember(Name = "gridStatus", EmitDefaultValue = true)]
        public GridStatusEnum? GridStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="View" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="columns">columns.</param>
        /// <param name="gridId">gridId.</param>
        /// <param name="gridStatus">gridStatus.</param>
        /// <param name="name">name.</param>
        /// <param name="records">records.</param>
        public View(string id = default, List<ViewColumn> columns = default, string gridId = default, GridStatusEnum? gridStatus = default, string name = default, List<Record> records = default)
        {
            this.Id = id;
            this.Columns = columns;
            this.GridId = gridId;
            this.GridStatus = gridStatus;
            this.Name = name;
            this.Records = records;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [DataMember(Name = "columns", EmitDefaultValue = true)]
        public List<ViewColumn> Columns { get; set; }

        /// <summary>
        /// Gets or Sets GridId
        /// </summary>
        [DataMember(Name = "gridId", EmitDefaultValue = true)]
        public string GridId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Records
        /// </summary>
        [DataMember(Name = "records", EmitDefaultValue = true)]
        public List<Record> Records { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class View {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  GridId: ").Append(GridId).Append("\n");
            sb.Append("  GridStatus: ").Append(GridStatus).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
